name: Go Init
description: Initializes go and runs go generate

runs:
  using: "composite"
  steps:
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.x
        check-latest: true

    - name: Checkout
      uses: actions/checkout@v4
      with:
        repository: overmindtech/aws-source
        path: ./aws-source

    - name: Checkout
      uses: actions/checkout@v4
      with:
        repository: overmindtech/k8s-source
        path: ./k8s-source

    - name: Move sources in place
      shell: bash
      run: |
        mv -v aws-source ..
        mv -v k8s-source ..

    - name: Go Generate
      shell: bash
      run: |
        go generate ./...
        if [ -z "$(git status --porcelain)" ]; then
          echo "No pending changes from 'go generate'"
        else
          echo "Pending changes from 'go generate' found, please run 'go generate ./...' and commit the changes"
          git status
          exit 1
        fi
        cat cmd/commit.txt
