name: goreleaser-release

on:
  push:
    tags:
      - 'v*'
jobs:
  # Actually release the binaries including signing them
  release:
    runs-on: apple-certs
    if: ${{ github.event_name != 'pull_request' }}
    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Gon from fork
        run: |
          curl -o gon -L https://github.com/dylanratcliffe/gon/releases/download/apple-silicon-fix/gon
          chmod +x gon 

      - name: Go Init
        uses: ./.github/actions/go_init
        with:
          cache: false

      - run: go run main.go --version

      - name: Run GoReleaser (publish)
        uses: goreleaser/goreleaser-action@v5
        with:
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          AC_PASSWORD: ${{ secrets.APPLE_AC_PASSWORD }}
