name: goreleaser

on:
  pull_request:
  push:
    tags:
      - 'v*'
jobs:
  goreleaser:
    runs-on: apple-certs
    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Gon using homebrew
        run: brew install Bearer/tap/gon

      - name: Go Init
        uses: ./.github/actions/go_init

      - run: go run main.go --version

      - name: Run GoReleaser (publish)
        uses: goreleaser/goreleaser-action@v5
        if: ${{ github.event_name != 'pull_request' }}
        with:
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run GoReleaser (dry run)
        uses: goreleaser/goreleaser-action@v5
        if: ${{ github.event_name == 'pull_request' }}
        with:
          version: latest
          args: release --clean --snapshot --skip=publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          AC_PASSWORD: ${{ secrets.APPLE_AC_PASSWORD }}

      - name: Upload assets
        uses: actions/upload-artifact@v4
        # only upload artifacts on pull requests
        if: ${{ github.event_name == 'pull_request' }}
        with:
          name: test-release
          path: dist/*
