name: goreleaser-release

on:
  push:
    tags:
      - 'v*'
jobs:
  # Actually release the binaries including signing them
  release:
    runs-on: ubuntu-latest
    if: ${{ github.event_name != 'pull_request' }}
    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # - name: Install Gon from fork
      #   run: |
      #     curl -o gon -L https://github.com/dylanratcliffe/gon/releases/download/apple-silicon-fix/gon
      #     chmod +x gon 

      - name: Go Init
        uses: ./.github/actions/go_init
        with:
          cache: false

      - run: go run main.go --version

      - name: Run GoReleaser (publish)
        uses: goreleaser/goreleaser-action@v5
        with:
          version: latest
          args: release --clean --skip sign
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          AC_PASSWORD: ${{ secrets.APPLE_AC_PASSWORD }}
      
  bump-formula:
    runs-on: ubuntu-latest
    if: ${{ github.event_name != 'pull_request' }}
    steps:
      - name: Update Homebrew formula
        uses: dawidd6/action-homebrew-bump-formula@v3
        with:
          # Required, custom personal GitHub access token with only the 'public_repo' scope enabled
          token: ${{secrets.CUSTOM_PERSONAL_ACCESS_TOKEN}}
          # Bump all outdated formulae in this tap
          tap: overmindtech/homebrew-overmind
          # Bump only these formulae if outdated
          formula: overmind-cli
          # Need to set this input if want to use `brew livecheck`
          livecheck: true