name: Run Tests
on: push
jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    env:
      CGO_ENABLED: 0

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Go Init
        uses: ./.github/actions/go_init

      - name: Get dependencies
        run: |
          go get -v -t -d ./...

      - name: Go Test
        run: |
          go run main.go --version
          go test -v -timeout 5m ./...

  golangci:
    name: lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Go Init
        uses: ./.github/actions/go_init

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.56.1
          args: --timeout 3m
          skip-pkg-cache: true # golangci-lint-action caching conflicts with the setup-go cache and `go get` above. See https://github.com/golangci/golangci-lint-action/issues/23
