name: Run Tests
on: push
jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    env:
      CGO_ENABLED: 0
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: 1.x

      - name: Get dependencies
        run: |
          go get -v -t -d ./...

      - name: Go Vet
        run: go vet ./...

      - name: Go Test
        run: |
          go test -v -timeout 5m ./...
