name: Run Tests
on: push
jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    env:
      CGO_ENABLED: 0
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Go Init
        uses: ./.github/actions/go_init

      - name: Get dependencies
        run: |
          go get -v -t -d ./...

      - name: Go Vet
        run: go vet ./...

      - name: Go Test
        run: |
          go test -v -timeout 5m ./...

  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Go Init
        uses: ./.github/actions/go_init

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.53
